'use client';

import { useState } from 'react';
import { toast } from 'sonner';
import { createDocument } from '@/lib/document-storage';
import {
  FileText,
  Loader2,
  Copy,
  CheckCircle2,
  Save,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { getApiUrl } from '@/lib/api-url';

interface SOAPExportCardProps {
  caseText: string;
  topRecommendation: string;
  acuteManagement?: {
    immediate_actions?: string[];
    monitoring_plan?: string[];
    disposition?: string;
  };
  treatmentOptions: Array<{ name: string; verdict: string }>;
}

export function SOAPExportCard({
  caseText,
  topRecommendation,
  acuteManagement,
  treatmentOptions,
}: SOAPExportCardProps) {
  const [soapNote, setSoapNote] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const generateSOAP = async () => {
    setIsLoading(true);
    try {
      const apiUrl = getApiUrl();
      const response = await fetch(`${apiUrl}/api/chart/enhance`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          raw_text: caseText,
          note_type: 'soap',
          patient_context: {
            top_recommendation: topRecommendation,
            treatments: treatmentOptions.map(t => `${t.name} (${t.verdict})`).join(', '),
            disposition: acuteManagement?.disposition || '',
          },
        }),
      });

      if (!response.ok) {
        // Fallback: generate locally
        const note = generateLocalSOAP();
        setSoapNote(note);
        return;
      }

      const data = await response.json();
      setSoapNote(data.enhanced_text || data.text || generateLocalSOAP());
    } catch {
      // Fallback to local generation
      setSoapNote(generateLocalSOAP());
    } finally {
      setIsLoading(false);
    }
  };

  const generateLocalSOAP = () => {
    const recommended = treatmentOptions.filter(t => t.verdict === 'recommended');
    const actions = acuteManagement?.immediate_actions || [];
    const monitoring = acuteManagement?.monitoring_plan || [];

    return `SUBJECTIVE:
${caseText.slice(0, 500)}${caseText.length > 500 ? '...' : ''}

OBJECTIVE:
[See parsed case findings above]

ASSESSMENT:
Primary recommendation: ${topRecommendation}
Recommended treatments: ${recommended.map(t => t.name).join(', ') || 'See analysis'}

PLAN:
${actions.length > 0 ? `Immediate actions:\n${actions.map((a, i) => `${i + 1}. ${a}`).join('\n')}` : ''}
${monitoring.length > 0 ? `\nMonitoring:\n${monitoring.map(m => `- ${m}`).join('\n')}` : ''}
${acuteManagement?.disposition ? `\nDisposition: ${acuteManagement.disposition}` : ''}

---
Generated by MedMink | For educational purposes only | ${new Date().toLocaleDateString()}`;
  };

  const handleCopy = async () => {
    if (soapNote) {
      await navigator.clipboard.writeText(soapNote);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" />
            <CardTitle className="text-base">SOAP Note</CardTitle>
          </div>
          <div className="flex gap-2">
            {soapNote && (
              <>
                <Button variant="outline" size="sm" onClick={() => {
                  createDocument({
                    type: 'soap_note',
                    title: `SOAP Note — ${new Date().toLocaleDateString()}`,
                    content: soapNote,
                  });
                  toast.success('SOAP note saved');
                }}>
                  <Save className="w-3.5 h-3.5 mr-1.5" /> Save
                </Button>
                <Button variant="outline" size="sm" onClick={handleCopy}>
                  {copied ? (
                    <><CheckCircle2 className="w-3.5 h-3.5 mr-1.5 text-green-500" /> Copied</>
                  ) : (
                    <><Copy className="w-3.5 h-3.5 mr-1.5" /> Copy</>
                  )}
                </Button>
              </>
            )}
            <Button
              variant="outline"
              size="sm"
              onClick={generateSOAP}
              disabled={isLoading}
            >
              {isLoading ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin mr-1.5" />
              ) : (
                <FileText className="w-3.5 h-3.5 mr-1.5" />
              )}
              {soapNote ? 'Regenerate' : 'Generate'} SOAP
            </Button>
          </div>
        </div>
      </CardHeader>
      {soapNote && (
        <CardContent>
          <Textarea
            value={soapNote}
            onChange={(e) => setSoapNote(e.target.value)}
            className="font-mono text-sm bg-muted/50 leading-relaxed min-h-[300px] resize-y"
            rows={soapNote.split('\n').length + 2}
          />
        </CardContent>
      )}
    </Card>
  );
}
